# Site settings
name: Alyssa Katz
description: Client Engineer for The Pokémon Trading Card Game Live
url: "http://alyssakatz.dev"

# about 5 elements are recomended
github_username:  alyssakatz
linkedin_username: alyssa-katz
resume_url: https://github.com/alyssakatz/alyssakatz.github.io/blob/30b78f83c8eb743471420cd95d1dc9ed1270a8da/AlyssaKatzResume2025-General.pdf
email: alyssa@alyssakatz.dev

avatar: yes
avatar_img_path: "https://avatars2.githubusercontent.com/u/15315741"

front_img: yes
front_img_path: "imgs/background.jpg"

# Build settings
markdown: kramdown
permalink: pretty

# Manifest settings
manifest_name: Alyssa Katz
manifest_short_name: A. Katz
manifest_lang: en
manifest_background_color: fdfdfd
manifest_theme_color: 2a7ae2
manifest_display: standalone
